#!/usr/bin/env bash

# Create a new directory and enter it
function mkcd() {
	mkdir -p "$@" && cd "$1"
}

# Go to directory and list it
function cdls() {
	cd "$1" && ls
}

# Change working directory to the top-most Finder window location
function cdf() { # short for `cdfinder`
	cd "$(osascript -e 'tell app "Finder" to POSIX path of (insertion location as alias)')"
}

# Open man page as PDF
function manpdf() {
	man -t "$1" | open -f -a /Applications/Preview.app/
}

# Extra many types of compressed packages
# Credit: http://nparikh.org/notes/zshrc.txt
extract() {
	if [ -f "$1" ]; then
		case "$1" in
			*.tar.bz2)  tar -jxvf "$1"                        ;;
			*.tar.gz)   tar -zxvf "$1"                        ;;
			*.bz2)      bunzip2 "$1"                          ;;
			*.dmg)      hdiutil mount "$1"                    ;;
			*.gz)       gunzip "$1"                           ;;
			*.tar)      tar -xvf "$1"                         ;;
			*.tbz2)     tar -jxvf "$1"                        ;;
			*.tgz)      tar -zxvf "$1"                        ;;
			*.zip)      unzip "$1"                            ;;
			*.ZIP)      unzip "$1"                            ;;
			*.pax)      cat "$1" | pax -r                     ;;
			*.pax.Z)    uncompress "$1" --stdout | pax -r     ;;
			*.Z)        uncompress "$1"                       ;;
			*) echo "'$1' cannot be extracted/mounted via extract()" ;;
		esac
	else
		echo "'$1' is not a valid file to extract"
	fi
}

# Determine size of a file or total size of a directory
function fsize() {
	if du -b /dev/null > /dev/null 2>&1; then
		local ARG=-sbh
		local DU=du
	elif gdu -b /dev/null > /dev/null 2>&1; then
		local ARG=-sbh
		local DU=gdu
	else
		local ARG=-sh
		local DU=du
	fi

	if [[ -n "$@" ]]; then
		$DU $ARG -- "$@"
	else
		$DU $ARG .[^.]* ./*
	fi
}

# Open new tab and focus
function newtab() {
	osascript 2>/dev/null <<EOF
	tell application "System Events"
	tell process "Terminal" to keystroke "t" using command down
	end
	tell application "Terminal"
	activate
	do script with command " cd \"$PWD\"; $*" in window 0
	end tell
EOF
}
