#!/usr/bin/env bash

export TERM='xterm-256color'

export LSCOLORS='BxexhxDxcxhxhxhxhxBxBx'

export EDITOR='nano'

# Bash history
export HISTSIZE="32768"
export HISTFILESIZE="32768"
export HISTCONTROL="ignoredups"

# Locale
export LANG="en_US.UTF-8"
export LANGUAGE="en_US:en_GB:en"
export LC_ALL="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
export LC_MEASUREMENT="en_NZ.UTF" # Force metric system

# Man pager, bold
export LESS_TERMCAP_md="${bashc_bold}${bashc_blue}"
export LESS_TERMCAP_me="${bashc_reset}"
# Man pager, underline
export LESS_TERMCAP_us="${bashc_underline}${bashc_red}"
export LESS_TERMCAP_ue="${bashc_reset}"
