#!/usr/bin/env bash

# Easier navigation: .., ..., ...., ..... and --
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias -- --="cd - > /dev/null"

# Shortcuts
alias cdd="cd ~/Dropbox"
alias cdp="cd ~/Dropbox/Projects"
alias cddl="cd ~/Downloads"
alias cddt="cd ~/Desktop"

# List all files colorized in long format
alias lsl="ls -lhG"

# List all files colorized in long format, including dot files
alias lsa="ls -lahG"

# List only directories
alias lsd="ls -la | grep --color=never '^d'"

# Always use color output for `ls`
alias ls="command ls -G"

# Always use color output for `tree`
alias tree="command tree -C --dirsfirst"

# Always use color output for `tree`
alias treea="command tree -aC --dirsfirst -I '.git'"

# Always enable colored `grep` output
# Note: `GREP_OPTIONS="--color=auto"` is deprecated, hence the alias usage.
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# Enable aliases to be sudo’ed
alias sudo='sudo '

# macOS has no `md5sum`, so use `md5` as a fallback
command -v md5sum > /dev/null || alias md5sum="md5"

# macOS has no `sha1sum`, so use `shasum` as a fallback
command -v sha1sum > /dev/null || alias sha1sum="shasum"

# IP addresses
alias myip="dig +short myip.opendns.com @resolver1.opendns.com"
alias localip="ipconfig getifaddr en0"

# Get macOS Software Updates, and update installed Ruby gems, Homebrew, npm, and their installed packages
alias update_everything='sudo softwareupdate -i -a; brew update; brew upgrade --all; brew cleanup'

# Show/hide hidden files in Finder
alias showhidden="defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder"
alias hidehidden="defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder"

# Clean up LaunchServices to remove duplicates in the “Open With” menu
alias lscleanup="/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user && killall Finder"

# Merge PDF files
# Usage: `mergepdf -o output.pdf input{1,2,3}.pdf`
alias mergepdf='/System/Library/Automator/Combine\ PDF\ Pages.action/Contents/Resources/join.py'

# Ring the terminal bell, and put a badge on Terminal.app’s Dock icon
# (useful when executing time-consuming commands)
alias alert="tput bel"

# Lock the screen (when going AFK)
alias afk="/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend"

# Reload the shell (i.e. invoke as a login shell)
alias reloadshell="exec $SHELL -l"

# Print each PATH entry on a separate line
alias pathprint='echo -e ${PATH//:/\\n}'

# Load R quietly
alias Rq='R --quiet'
